// This file is automatically generated by otelc pin for tracking instrumentations.
// Additional instrumentation imports may be added manually.

//go:build tools

//go:generate go tool otelc pin --generate
package tools

import (
	_ "go.opentelemetry.io/otelc/instrumentation/go.opentelemetry.io/otel"
	_ "go.opentelemetry.io/otelc/instrumentation/go.opentelemetry.io/otel/init"
	_ "go.opentelemetry.io/otelc/instrumentation/go.opentelemetry.io/otel/sdk/trace"
	_ "go.opentelemetry.io/otelc/instrumentation/go.opentelemetry.io/otel/trace"
	_ "go.opentelemetry.io/otelc/instrumentation/google.golang.org/grpc/client"
	_ "go.opentelemetry.io/otelc/instrumentation/google.golang.org/grpc/server"
	_ "go.opentelemetry.io/otelc/instrumentation/log"
	_ "go.opentelemetry.io/otelc/instrumentation/log/slog"
	_ "go.opentelemetry.io/otelc/instrumentation/net/http/client"
	_ "go.opentelemetry.io/otelc/instrumentation/net/http/server"
	_ "go.opentelemetry.io/otelc/instrumentation/runtime"
)
